### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by mabrasil** [jcalisson/pacman#2]
I couldn't find any licensing information here and as an open source project it is good to have this well defined.

If you're still in doubt about which license to choose, I'd suggest you [this site](http://choosealicense.com/). 

Once you've chosen you can add a copy of the license to your repo - a `LICENSE.md` file - and update the [License section](https://github.com/mabrasil/pacman#license) I proposed in #1.

**Comment by jcalisson** [comment]
Added! Thank you!
