### ISSUE TITLE
Translate project into English

### ISSUE THREAD

**Issue by mabrasil** [jcalisson/pacman#3]
As you can see in some [posts through the web](http://www.akitaonrails.com/2008/07/31/tradu-o-por-que-voc-n-o-deve-codificar-em-portugu-s), writing code in Portuguese - or in other languages than English.

There are many good reasons to translate this project into English - mainly since it's an open source one.

I'd also recommend you keeping not only the code or documentation but also the commit messages, issues and PRs in English.

**Comment by jcalisson** [comment]
Done. Thanks a lot! :D
